/**
 * ウイスキーの分類データと銘柄データ。
 * profile は 0〜5 の 5 段階（peat=スモーキーさ / sweet=甘さ / body=ボディ / fruit=果実感）。
 * price は参考価格帯（700ml 前後・国内小売の目安）。
 */

const CATEGORIES = [
  {
    id: 'scotch',
    name: 'スコッチウイスキー',
    nameEn: 'Scotch Whisky',
    country: 'イギリス / スコットランド',
    emoji: '🥃',
    summary:
      'ウイスキーの原点にして世界最大の生産地。ピート（泥炭）由来のスモーキーな香りと、地域ごとに大きく異なる個性が魅力。',
    features: [
      'スコットランド国内で糖化・発酵・蒸溜し、容量700L以下のオーク樽で3年以上熟成させることが法律で定められている',
      '瓶詰め時のアルコール度数は40%以上',
      '大麦麦芽のみを単一蒸溜所で造る「シングルモルト」と、グレーン原酒を混ぜた「ブレンデッド」が二大潮流',
      'ピートを焚いて麦芽を乾燥させる伝統から、正露丸・煙・潮を思わせる香りが生まれる',
      'シェリー樽・バーボン樽など熟成樽の使い分けで味わいを設計する文化が発達している',
    ],
    regions: [
      { name: 'アイラ', desc: '強烈なピートスモークとヨード香。海藻や潮の風味を伴う個性派の聖地。' },
      { name: 'スペイサイド', desc: '蒸溜所が最も密集する銘醸地。華やかでフルーティー、シェリー樽熟成の名手が多い。' },
      { name: 'ハイランド', desc: '広大で作風も多様。全体にバランスが良く、ヒースやハチミツを思わせるものが多い。' },
      { name: 'ローランド', desc: '軽快で穏やか。3回蒸溜の伝統もあり、入門に向く優しい味わい。' },
      { name: 'キャンベルタウン', desc: 'かつての一大産地。塩気とほのかなピート、油分のある独特のコクを持つ。' },
      { name: 'アイランズ', desc: 'スカイ島・オークニー諸島など。潮風とスパイス、中程度のスモークが特徴。' },
    ],
    pairing: 'スモーキー系は生ハム・燻製・ブルーチーズ、シェリー系はドライフルーツやチョコレートと好相性。',
    howto: 'まずはストレートで香りを取り、加水（トワイスアップ）で開く香りの変化を楽しむのが王道。',
  },
  {
    id: 'irish',
    name: 'アイリッシュウイスキー',
    nameEn: 'Irish Whiskey',
    country: 'アイルランド',
    emoji: '🍀',
    summary:
      'なめらかで軽やか、雑味の少ないクリーンな味わい。ピートを使わない造りが主流で、ウイスキー入門に最適。',
    features: [
      '「whiskey」と e を入れて綴るのが慣例',
      '3回蒸溜による軽快でスムースな酒質が伝統',
      '未発芽の大麦を用いる「シングルポットスチル」はアイルランド固有のスタイルで、オイリーでスパイシーな厚みを生む',
      'ピートを焚かないため、スモーキーさは基本的にごく穏やか',
      '木樽で3年以上熟成することが定められている',
    ],
    regions: [
      { name: 'ミドルトン', desc: 'ジェムソンやレッドブレストを生む南部の巨大蒸溜所。ポットスチル系の中心地。' },
      { name: 'ブッシュミルズ', desc: '北アイルランド。世界最古級の蒸溜免許を持ち、繊細で軽快な作風。' },
      { name: 'クーリー', desc: '例外的にピーテッド麦芽を使うコネマラなど、実験的な銘柄を輩出。' },
    ],
    pairing: 'そのままはもちろん、アイリッシュコーヒーやハイボールなど混ぜても崩れない懐の深さ。',
    howto: 'まずはストレートかロックで。クセが少ないためソーダ割りにしても香りが素直に立つ。',
  },
  {
    id: 'bourbon',
    name: 'バーボンウイスキー',
    nameEn: 'Bourbon Whiskey',
    country: 'アメリカ / 主にケンタッキー州',
    emoji: '🌽',
    summary:
      'トウモロコシ由来の甘い香りと、内側を焦がした新樽がもたらすバニラ・キャラメル香。力強くリッチな味わい。',
    features: [
      '原料の51%以上がトウモロコシであること',
      '内側を焦がした（チャーした）新品のオーク樽で熟成させること',
      '蒸溜時80%以下、樽詰め時62.5%以下、瓶詰め時40%以上のアルコール度数',
      'アメリカ国内で造られること（州は問わないが、事実上ケンタッキー州が中心）',
      '新樽のみを使うため、樽由来のバニラ・キャラメル・ココナッツ香が非常に強く出る',
    ],
    regions: [
      { name: 'ケンタッキー州', desc: '石灰岩層で濾過された硬水と寒暖差の大きい気候。バーボンの約95%を生産。' },
      { name: 'その他の州', desc: '近年はクラフト蒸溜所が全米に拡大。地ビール的な小規模生産が活況。' },
    ],
    pairing: 'BBQ・スペアリブ・ナッツ・ダークチョコレート。甘辛い味付けの料理と好相性。',
    howto: 'ロックで甘みを締めるか、ハイボール。ミントジュレップなどカクテルの土台にも最適。',
  },
  {
    id: 'tennessee',
    name: 'テネシーウイスキー',
    nameEn: 'Tennessee Whiskey',
    country: 'アメリカ / テネシー州',
    emoji: '🪵',
    summary:
      'バーボンの条件を満たしたうえで、サトウカエデの炭で濾過する「チャコール・メロウイング」を経た、まろやかな一群。',
    features: [
      'バーボンの製造要件をすべて満たしていること',
      'テネシー州内で製造すること',
      '樽詰め前にサトウカエデの木炭で濾過する「リンカーン・カウンティ・プロセス」を行うこと',
      '炭濾過により雑味と刺激が削がれ、バーボンより丸くスムースな口当たりになる',
      '甘いバニラ香に、香ばしいコーンとほのかな煙香が重なる',
    ],
    regions: [
      { name: 'リンチバーグ', desc: 'ジャックダニエルの本拠地。石灰岩の洞窟湧水を仕込み水に使う。' },
      { name: 'カスケードホロウ', desc: 'ジョージ・ディッケルの拠点。冷却してから炭濾過する独自製法をとる。' },
    ],
    pairing: 'ハンバーガー、フライドチキン、コーラとの相性は鉄板。',
    howto: 'コークハイやハイボールで気軽に。ストレートだと甘さとまろやかさがよく分かる。',
  },
  {
    id: 'rye',
    name: 'ライウイスキー',
    nameEn: 'Rye Whiskey',
    country: 'アメリカ / カナダ',
    emoji: '🌾',
    summary:
      'ライ麦由来のスパイシーでドライな味わい。禁酒法以前のアメリカの主役で、近年クラシックカクテル復権とともに再注目。',
    features: [
      'アメリカ産は原料の51%以上がライ麦であること',
      'バーボン同様、内側を焦がした新樽で熟成させる',
      '黒胡椒・シナモン・ディルを思わせるスパイス感と、締まったドライな骨格',
      '甘さより辛口の輪郭が立ち、カクテルにすると味がぼやけない',
      'カナダでは「ライ」がカナディアンウイスキー全般の別称として使われることもある',
    ],
    regions: [
      { name: 'ケンタッキー州', desc: '大手バーボンメーカーが手掛けるライ。比較的まろやかで甘みも残る。' },
      { name: 'ペンシルベニア / メリーランド', desc: '「モノンガヒラ」と呼ばれる歴史的な本場。よりドライで硬派な作風。' },
    ],
    pairing: 'スパイスの効いた料理、ライ麦パンとパストラミ、燻製肉。',
    howto: 'マンハッタン、サゼラック、オールドファッションドといった定番カクテルの主役に。',
  },
  {
    id: 'japanese',
    name: 'ジャパニーズウイスキー',
    nameEn: 'Japanese Whisky',
    country: '日本',
    emoji: '🗾',
    summary:
      'スコッチを手本にしつつ、繊細な香味設計と食事との調和を追求した日本独自のスタイル。世界的な評価と品薄が続く。',
    features: [
      '1923年の山崎蒸溜所建設が本格的な始まり。竹鶴政孝と鳥井信治郎が礎を築いた',
      '一つの蒸溜所で多彩な原酒を造り分け、自社内でブレンドを完結させる「自己完結型」が特徴',
      'ミズナラ樽熟成による白檀・伽羅を思わせるオリエンタルな香りは日本独自の個性',
      '2021年に日本洋酒酒造組合が表示基準を制定し、国内での糖化・発酵・蒸溜・3年以上の熟成が要件となった',
      'ハイボール文化により、食中酒としての設計思想が強い',
    ],
    regions: [
      { name: '山崎 / 白州（サントリー）', desc: '京都郊外の名水地と南アルプスの森。華やかな山崎、爽快な白州。' },
      { name: '余市 / 宮城峡（ニッカ）', desc: '石炭直火蒸溜の力強い余市、蒸気間接蒸溜の華やかな宮城峡。' },
      { name: '秩父ほかクラフト', desc: 'イチローズモルトを筆頭に、小規模蒸溜所が全国で急増中。' },
    ],
    pairing: '和食全般。刺身、天ぷら、焼き鳥。ハイボールにすると出汁の料理を邪魔しない。',
    howto: 'ハイボールが最も普及した飲み方。高級銘柄はストレートかトワイスアップで香りを味わう。',
  },
  {
    id: 'canadian',
    name: 'カナディアンウイスキー',
    nameEn: 'Canadian Whisky',
    country: 'カナダ',
    emoji: '🍁',
    summary:
      '5大ウイスキーの中で最も軽快でクセがない。カクテルベースやハイボールとして圧倒的に使いやすい。',
    features: [
      'カナダ国内で、容量700L以下の木樽で3年以上熟成させること',
      '風味の主体となる「フレーバリングウイスキー」と、軽いベースの「ベースウイスキー」を後からブレンドする独自方式',
      'ライ麦の使用比率が高く、軽い中にもかすかなスパイス感がある',
      '5大ウイスキーの中でもっともライトでスムース',
      '禁酒法時代にアメリカへ大量に流れ込み、北米のカクテル文化を支えた',
    ],
    regions: [
      { name: 'オンタリオ', desc: 'カナディアンクラブの本拠地ウィンザー。軽快でクリーンな作風。' },
      { name: 'マニトバ / アルバータ', desc: 'クラウンローヤルやアルバータ。ライ麦の産地に近く、スパイシーさが残る。' },
    ],
    pairing: 'クセが少ないため料理を選ばない。軽い前菜からデザートまで。',
    howto: 'ハイボール、ジンジャーエール割り、マンハッタンなど。氷を効かせて軽やかに。',
  },
  {
    id: 'world',
    name: 'ワールドウイスキー',
    nameEn: 'World Whisky',
    country: '台湾 / インド / 北欧 ほか',
    emoji: '🌏',
    summary:
      '5大産地以外の新興地。温暖な気候による超速熟成や、その土地ならではの原料・樽で個性を打ち出す。',
    features: [
      '台湾・インドなど高温多湿の地域では熟成が数倍速く進み、若い年数でも濃厚な味わいになる',
      '一方で天使の分け前（樽内の蒸発量）が非常に多く、生産コストは高い',
      '北欧では地元産の泥炭やジュニパーで麦芽を燻すなど、地域固有の香味づけを行う',
      '国際コンペティションで5大産地を上回る評価を得る銘柄が続出し、勢力図が変わりつつある',
    ],
    regions: [
      { name: '台湾', desc: 'カバランが牽引。亜熱帯の急速熟成による濃密なトロピカルフルーツ香。' },
      { name: 'インド', desc: 'アムルット、ポールジョン。高地の気候と現地大麦による厚みのある味わい。' },
      { name: '北欧', desc: 'スウェーデンのマクミラなど。地元産オークやジュニパー燻製の個性派。' },
    ],
    pairing: '濃厚な果実香を活かして、ドライフルーツやチーズ、デザートと合わせるのも面白い。',
    howto: '度数が高いものが多いので、少量の加水で香りを開かせるのがおすすめ。',
  },
];

const BRANDS = [
  /* ============ スコッチ ============ */
  {
    id: 'laphroaig10', cat: 'scotch', name: 'ラフロイグ 10年', nameEn: 'Laphroaig 10 Year Old',
    sub: 'アイラ', type: 'シングルモルト', abv: 43, price: '5,000〜7,000円',
    tags: ['スモーキー', 'ヨード', '正露丸'], profile: { peat: 5, sweet: 2, body: 4, fruit: 1 },
    desc: '「好きか嫌いか、中間はない」と言われるアイラの象徴。ヨードと消毒液を思わせる強烈なピート香の奥に、驚くほど甘くクリーミーな麦の芯がある。英国王室御用達。',
    tasting: { nose: '磯の香り、正露丸、焚き火の煙', palate: '力強いスモークと海の塩気、奥にバニラの甘み', finish: '長く煙たく、じんわり甘い余韻' },
  },
  {
    id: 'ardbeg10', cat: 'scotch', name: 'アードベッグ 10年', nameEn: 'Ardbeg 10 Year Old',
    sub: 'アイラ', type: 'シングルモルト', abv: 46, price: '6,000〜8,000円',
    tags: ['スモーキー', 'ノンチルフィルタード', 'レモン'], profile: { peat: 5, sweet: 2, body: 4, fruit: 2 },
    desc: 'ピートの強さでは世界最強クラスながら、驚くほど澄んだレモンやライムの酸が背骨を通す。冷却濾過をしない46度のボトリングで、粘性のある濃密な口当たり。',
    tasting: { nose: '煤けた煙、レモンピール、タール', palate: 'スモークとシトラスの拮抗、ビターチョコ', finish: '長大でクリーン、煙が尾を引く' },
  },
  {
    id: 'lagavulin16', cat: 'scotch', name: 'ラガヴーリン 16年', nameEn: 'Lagavulin 16 Year Old',
    sub: 'アイラ', type: 'シングルモルト', abv: 43, price: '9,000〜13,000円',
    tags: ['スモーキー', 'シェリー', '重厚'], profile: { peat: 5, sweet: 3, body: 5, fruit: 2 },
    desc: 'アイラの重鎮。16年の熟成がピートの角を丸め、シェリー樽由来の濃厚な甘みと一体化させた。「アイラのキング」と称される完成度で、贈り物にも選ばれる一本。',
    tasting: { nose: '深い煙、ドライフルーツ、革', palate: '濃密で油分のあるスモーク、干しぶどうの甘み', finish: '極めて長く、暖かいスモークが残る' },
  },
  {
    id: 'bowmore12', cat: 'scotch', name: 'ボウモア 12年', nameEn: 'Bowmore 12 Year Old',
    sub: 'アイラ', type: 'シングルモルト', abv: 40, price: '4,500〜6,000円',
    tags: ['スモーキー', 'バランス', '入門向け'], profile: { peat: 3, sweet: 3, body: 3, fruit: 3 },
    desc: 'アイラ最古の蒸溜所。「アイラの女王」と呼ばれる通り、スモークがやや穏やかで、レモンハチミツのような優しい甘さと調和する。アイラ入門の定番。',
    tasting: { nose: '穏やかな潮風、ハチミツレモン', palate: 'ライトなスモーク、麦の甘み、微かな塩気', finish: '中程度で心地よいスモーク' },
  },
  {
    id: 'macallan12', cat: 'scotch', name: 'ザ・マッカラン 12年 シェリーオーク', nameEn: 'The Macallan 12 Sherry Oak',
    sub: 'スペイサイド', type: 'シングルモルト', abv: 40, price: '10,000〜16,000円',
    tags: ['シェリー', '芳醇', '高級'], profile: { peat: 0, sweet: 4, body: 4, fruit: 5 },
    desc: '「シングルモルトのロールスロイス」。スペイン産オークのシェリー樽で熟成させ、干しぶどうやオレンジの濃厚な甘みが層になる。近年は価格高騰が著しい。',
    tasting: { nose: 'ドライフルーツ、シェリー、バニラ', palate: 'リッチなレーズン、オレンジピール、スパイス', finish: '甘くふくよかで長い' },
  },
  {
    id: 'glenfiddich12', cat: 'scotch', name: 'グレンフィディック 12年', nameEn: 'Glenfiddich 12 Year Old',
    sub: 'スペイサイド', type: 'シングルモルト', abv: 40, price: '3,500〜5,000円',
    tags: ['洋梨', '軽快', '入門向け'], profile: { peat: 0, sweet: 3, body: 2, fruit: 4 },
    desc: '世界で最も売れているシングルモルト。青リンゴや洋梨を思わせる爽やかなフルーツ香で、シングルモルトの入り口として長く支持されている。',
    tasting: { nose: '洋梨、青リンゴ、微かなオーク', palate: '軽快でフルーティー、バニラの甘み', finish: 'すっきりと爽やか' },
  },
  {
    id: 'glenlivet12', cat: 'scotch', name: 'ザ・グレンリベット 12年', nameEn: 'The Glenlivet 12 Year Old',
    sub: 'スペイサイド', type: 'シングルモルト', abv: 40, price: '3,500〜5,000円',
    tags: ['フローラル', '上品', '入門向け'], profile: { peat: 0, sweet: 3, body: 2, fruit: 4 },
    desc: '政府公認第1号蒸溜所という歴史を持つ「シングルモルトの原点」。花のような華やかさとパイナップルの甘酸っぱさが軽やかに広がる。',
    tasting: { nose: '白い花、パイナップル、バニラ', palate: 'なめらかでフローラル、ハチミツ', finish: '穏やかで上品' },
  },
  {
    id: 'glenmorangie10', cat: 'scotch', name: 'グレンモーレンジィ オリジナル 10年', nameEn: 'Glenmorangie Original 10',
    sub: 'ハイランド', type: 'シングルモルト', abv: 40, price: '4,000〜5,500円',
    tags: ['オレンジ', 'なめらか', '入門向け'], profile: { peat: 0, sweet: 4, body: 2, fruit: 4 },
    desc: 'スコットランド一背の高いポットスチルが生む、驚くほど繊細で軽やかな酒質。バーボン樽由来のバニラとオレンジの香りが特徴で、「完璧なくらいなめらか」と評される。',
    tasting: { nose: 'オレンジ、バニラ、桃', palate: 'クリーミーでシルキー、柑橘の甘み', finish: '穏やかで長く続く柑橘' },
  },
  {
    id: 'talisker10', cat: 'scotch', name: 'タリスカー 10年', nameEn: 'Talisker 10 Year Old',
    sub: 'アイランズ（スカイ島）', type: 'シングルモルト', abv: 45.8, price: '5,000〜7,000円',
    tags: ['潮', '黒胡椒', 'スモーキー'], profile: { peat: 4, sweet: 2, body: 4, fruit: 2 },
    desc: '「島のウイスキーの王」。フィニッシュに強烈な黒胡椒のスパイスが弾ける独特の個性で知られる。牡蠣に数滴垂らして食べる楽しみ方が有名。',
    tasting: { nose: '潮風、煙、乾いた麦', palate: '塩気とスモーク、力強い甘み', finish: '黒胡椒のスパイスが爆発する' },
  },
  {
    id: 'highlandpark12', cat: 'scotch', name: 'ハイランドパーク 12年', nameEn: 'Highland Park 12 Viking Honour',
    sub: 'アイランズ（オークニー）', type: 'シングルモルト', abv: 40, price: '5,000〜7,000円',
    tags: ['ヘザーハニー', 'バランス', 'ほのかな煙'], profile: { peat: 2, sweet: 4, body: 3, fruit: 3 },
    desc: '世界最北級の蒸溜所。ヘザー（エリカ）を含む島の泥炭で燻すため、甘く芳しい独特のスモークになる。甘み・スモーク・果実のバランスが極めて高いと評価される。',
    tasting: { nose: 'ヘザーハニー、甘い煙、シェリー', palate: 'ハチミツの甘みとほのかなスモーク', finish: 'なめらかで甘くスモーキー' },
  },
  {
    id: 'auchentoshan12', cat: 'scotch', name: 'オーヘントッシャン 12年', nameEn: 'Auchentoshan 12 Year Old',
    sub: 'ローランド', type: 'シングルモルト', abv: 40, price: '4,000〜5,500円',
    tags: ['3回蒸溜', '軽快', 'ナッツ'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: 'スコッチでは珍しい3回蒸溜を守り続けるローランドの蒸溜所。雑味が徹底的に削がれた、透明感のあるなめらかな味わい。',
    tasting: { nose: 'アーモンド、レモン、キャラメル', palate: '軽やかでクリーン、ナッツとトフィー', finish: '短めですっきり' },
  },
  {
    id: 'springbank10', cat: 'scotch', name: 'スプリングバンク 10年', nameEn: 'Springbank 10 Year Old',
    sub: 'キャンベルタウン', type: 'シングルモルト', abv: 46, price: '9,000〜15,000円',
    tags: ['塩気', 'オイリー', '入手難'], profile: { peat: 2, sweet: 3, body: 4, fruit: 3 },
    desc: '製麦から瓶詰めまで自社で一貫生産する稀有な蒸溜所。塩気とオイリーな質感、微かなピートが複雑に絡む唯一無二の味で、近年は入手困難が続く。',
    tasting: { nose: '潮、麦、微かな煙とフルーツ', palate: 'オイリーで塩気があり、複雑', finish: '長く塩気とスモークが残る' },
  },
  {
    id: 'jwblack', cat: 'scotch', name: 'ジョニーウォーカー ブラックラベル 12年', nameEn: 'Johnnie Walker Black Label',
    sub: 'ブレンデッド', type: 'ブレンデッド', abv: 40, price: '3,000〜4,500円',
    tags: ['ブレンデッド', 'スモーキー', '定番'], profile: { peat: 2, sweet: 3, body: 3, fruit: 3 },
    desc: '約40種の原酒を12年以上熟成させてブレンドした、世界のブレンデッドの基準。ほのかなスモークと甘みのバランスが良く、ハイボールでも味が痩せない。',
    tasting: { nose: 'ドライフルーツ、バニラ、微かな煙', palate: '厚みのある甘みとスモーク', finish: '中程度でスモーキー' },
  },
  {
    id: 'chivas12', cat: 'scotch', name: 'シーバスリーガル 12年', nameEn: 'Chivas Regal 12',
    sub: 'ブレンデッド', type: 'ブレンデッド', abv: 40, price: '2,500〜3,800円',
    tags: ['ブレンデッド', 'まろやか', 'ハチミツ'], profile: { peat: 0, sweet: 4, body: 3, fruit: 4 },
    desc: 'スペイサイドのストラスアイラを核とした、まろやかで華やかなブレンデッド。ハチミツと熟したリンゴの甘みがあり、スモーク感はほぼない。',
    tasting: { nose: 'ハチミツ、熟したリンゴ、バニラ', palate: 'なめらかでクリーミー、甘い', finish: '穏やかで丸い' },
  },
  {
    id: 'ballantines', cat: 'scotch', name: 'バランタイン ファイネスト', nameEn: "Ballantine's Finest",
    sub: 'ブレンデッド', type: 'ブレンデッド', abv: 40, price: '1,500〜2,200円',
    tags: ['ブレンデッド', 'コスパ', '定番'], profile: { peat: 1, sweet: 3, body: 2, fruit: 3 },
    desc: '40種以上の原酒を使う世界的ベストセラー。価格からは想像しにくい香りの複雑さがあり、ハイボールの土台として極めて優秀。',
    tasting: { nose: '青リンゴ、バニラ、微かなスモーク', palate: '軽快でバランスが良い', finish: 'すっきり短め' },
  },

  /* ============ アイリッシュ ============ */
  {
    id: 'jameson', cat: 'irish', name: 'ジェムソン スタンダード', nameEn: 'Jameson Irish Whiskey',
    sub: 'ミドルトン', type: 'ブレンデッド', abv: 40, price: '2,000〜2,800円',
    tags: ['スムース', '定番', '入門向け'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: '世界一売れているアイリッシュ。3回蒸溜によるなめらかさと、ポットスチル原酒由来のほのかなスパイスが同居する。ジェムソン・ジンジャーが定番の飲み方。',
    tasting: { nose: 'バニラ、洋梨、ナッツ', palate: 'とてもなめらか、甘くスパイシー', finish: '短くクリーン' },
  },
  {
    id: 'bushmills', cat: 'irish', name: 'ブッシュミルズ オリジナル', nameEn: 'Bushmills Original',
    sub: 'ブッシュミルズ', type: 'ブレンデッド', abv: 40, price: '2,000〜2,800円',
    tags: ['軽快', '歴史', '入門向け'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: '1608年の蒸溜免許を掲げる世界最古級の蒸溜所。モルト比率が高めで、軽やかながら麦の甘みとバニラの香りをしっかり感じられる。',
    tasting: { nose: 'バニラ、蜂蜜、青リンゴ', palate: '軽快でシルキー、ハチミツの甘み', finish: '穏やかでクリーン' },
  },
  {
    id: 'redbreast12', cat: 'irish', name: 'レッドブレスト 12年', nameEn: 'Redbreast 12 Year Old',
    sub: 'ミドルトン', type: 'シングルポットスチル', abv: 40, price: '7,000〜10,000円',
    tags: ['ポットスチル', 'シェリー', '名作'], profile: { peat: 0, sweet: 4, body: 4, fruit: 4 },
    desc: 'アイリッシュ固有のシングルポットスチルの最高峰と評される一本。シェリー樽由来のリッチな果実味に、未発芽大麦のオイリーでスパイシーな厚みが加わる。',
    tasting: { nose: 'ドライフルーツ、クリスマスケーキ、ナツメグ', palate: '濃厚でオイリー、スパイスと果実', finish: '長く複雑' },
  },
  {
    id: 'tullamore', cat: 'irish', name: 'タラモアデュー', nameEn: 'Tullamore D.E.W.',
    sub: 'タラモア', type: 'ブレンデッド', abv: 40, price: '2,000〜2,800円',
    tags: ['トリプルブレンド', '軽快', 'コスパ'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: 'ポットスチル・モルト・グレーンの3種をブレンドする「トリプルブレンド」。柔らかい口当たりで、アイリッシュコーヒーの定番ベースとしても知られる。',
    tasting: { nose: '青リンゴ、シトラス、バニラ', palate: '柔らかく穏やか、麦の甘み', finish: '軽快で短い' },
  },
  {
    id: 'connemara', cat: 'irish', name: 'コネマラ ピーテッド', nameEn: 'Connemara Peated Single Malt',
    sub: 'クーリー', type: 'シングルモルト', abv: 40, price: '4,000〜5,500円',
    tags: ['ピーテッド', '異色', 'ハチミツ'], profile: { peat: 3, sweet: 3, body: 3, fruit: 3 },
    desc: 'ピートを使わないのが常識のアイリッシュにあって、あえてピーテッド麦芽を使う異色の存在。スコッチほど強くない上品なスモークと、蜂蜜の甘さが共存する。',
    tasting: { nose: '甘い煙、蜂蜜、麦芽', palate: 'マイルドなスモークと蜂蜜、レモン', finish: '甘い煙が穏やかに続く' },
  },
  {
    id: 'greenspot', cat: 'irish', name: 'グリーンスポット', nameEn: 'Green Spot',
    sub: 'ミドルトン', type: 'シングルポットスチル', abv: 40, price: '7,000〜9,000円',
    tags: ['ポットスチル', '青リンゴ', '通好み'], profile: { peat: 0, sweet: 3, body: 3, fruit: 4 },
    desc: 'ダブリンの老舗食料品店ミッチェル&サンが手掛ける歴史的ボンダーズウイスキー。青リンゴのような瑞々しさとポットスチルの厚みが同居する。',
    tasting: { nose: '青リンゴ、ミント、バニラ', palate: '瑞々しくオイリー、スパイス', finish: '爽やかで長め' },
  },
  {
    id: 'teeling-sb', cat: 'irish', name: 'ティーリング スモールバッチ', nameEn: 'Teeling Small Batch',
    sub: 'ダブリン', type: 'ブレンデッド', abv: 46, price: '4,000〜5,500円',
    tags: ['ラム樽', 'クラフト', '46度'], profile: { peat: 0, sweet: 4, body: 3, fruit: 4 },
    desc: 'ダブリンに125年ぶりに誕生した蒸溜所。中米産ラム樽で後熟させることで、バニラとトロピカルな甘さが際立つ。46度・ノンチルフィルタードで骨格も明確。',
    tasting: { nose: 'バニラ、ラム、ドライフルーツ', palate: '甘く厚みがあり、スパイシー', finish: '甘く長い' },
  },

  /* ============ バーボン ============ */
  {
    id: 'makers', cat: 'bourbon', name: "メーカーズマーク", nameEn: "Maker's Mark",
    sub: 'ケンタッキー', type: 'バーボン', abv: 45, price: '3,000〜4,000円',
    tags: ['小麦', 'まろやか', '入門向け'], profile: { peat: 0, sweet: 5, body: 3, fruit: 2 },
    desc: 'ライ麦の代わりに冬小麦を使う「ウィーテッドバーボン」の代表格。バーボン特有の辛さが抑えられ、非常にまろやかで甘い。赤い封蝋が象徴。',
    tasting: { nose: 'バニラ、キャラメル、焼きたてパン', palate: 'まろやかで甘い、辛さが少ない', finish: '穏やかで甘い' },
  },
  {
    id: 'wildturkey8', cat: 'bourbon', name: 'ワイルドターキー 8年', nameEn: 'Wild Turkey 8 Year Old',
    sub: 'ケンタッキー', type: 'バーボン', abv: 50.5, price: '3,500〜4,500円',
    tags: ['ハイプルーフ', '力強い', '定番'], profile: { peat: 0, sweet: 4, body: 5, fruit: 2 },
    desc: '50.5度という高い度数と深いチャーの新樽が生む、圧倒的な骨太さ。バニラとキャラメルの甘さに、噛みごたえのあるオークとスパイスが乗る。',
    tasting: { nose: '濃いバニラ、キャラメル、オーク', palate: '力強く甘辛い、スパイシー', finish: '長く熱く、甘みが残る' },
  },
  {
    id: 'blantons', cat: 'bourbon', name: 'ブラントン シングルバレル', nameEn: "Blanton's Single Barrel",
    sub: 'ケンタッキー', type: 'バーボン', abv: 46.5, price: '10,000〜18,000円',
    tags: ['シングルバレル', '高級', '馬のキャップ'], profile: { peat: 0, sweet: 4, body: 4, fruit: 3 },
    desc: '世界初のシングルバレル・バーボン。樽ごとに瓶詰めするため個体差があり、8種の馬のフィギュアが並ぶボトルキャップの収集も人気。近年は価格が高騰。',
    tasting: { nose: 'バニラ、オレンジ、蜂蜜、オーク', palate: 'リッチでシルキー、柑橘とスパイス', finish: '長くドライで満足感がある' },
  },
  {
    id: 'fourroses', cat: 'bourbon', name: 'フォアローゼズ', nameEn: 'Four Roses',
    sub: 'ケンタッキー', type: 'バーボン', abv: 40, price: '1,800〜2,500円',
    tags: ['華やか', 'フローラル', 'コスパ'], profile: { peat: 0, sweet: 4, body: 2, fruit: 4 },
    desc: '2種のマッシュビルと5種の酵母から10タイプの原酒を造り分ける独自製法。バーボンとしては珍しく、フローラルでフルーティーな軽やかさが際立つ。',
    tasting: { nose: '薔薇、洋梨、バニラ', palate: '軽やかで華やか、甘くまろやか', finish: 'すっきり爽やか' },
  },
  {
    id: 'buffalotrace', cat: 'bourbon', name: 'バッファロートレース', nameEn: 'Buffalo Trace',
    sub: 'ケンタッキー', type: 'バーボン', abv: 45, price: '3,500〜5,000円',
    tags: ['バランス', '高評価', 'コスパ'], profile: { peat: 0, sweet: 4, body: 4, fruit: 3 },
    desc: '数々の伝説的ボトルを生む名門蒸溜所のフラッグシップ。価格に対する完成度が高く、「毎日飲めるバーボンの最適解」として国際的評価が非常に高い。',
    tasting: { nose: 'キャラメル、バニラ、ミント', palate: 'なめらかで厚みがあり、スパイスと甘みが調和', finish: '中程度で心地よい' },
  },
  {
    id: 'elijahcraig', cat: 'bourbon', name: 'エライジャ・クレイグ スモールバッチ', nameEn: 'Elijah Craig Small Batch',
    sub: 'ケンタッキー', type: 'バーボン', abv: 47, price: '4,500〜6,000円',
    tags: ['スモールバッチ', '濃厚', 'オーク'], profile: { peat: 0, sweet: 4, body: 5, fruit: 2 },
    desc: '「バーボンの父」の名を冠した銘柄。深く焦がした樽由来の濃厚なオーク香とスモーキーな甘みがあり、価格以上の重厚さを持つ。',
    tasting: { nose: '焦がしオーク、バニラ、燻した砂糖', palate: '濃厚で甘く、ウッディなスパイス', finish: '長くドライ、オークが残る' },
  },
  {
    id: 'knobcreek9', cat: 'bourbon', name: 'ノブクリーク 9年', nameEn: 'Knob Creek 9 Year Old',
    sub: 'ケンタッキー', type: 'バーボン', abv: 50, price: '4,000〜5,500円',
    tags: ['スモールバッチ', '50度', '濃厚'], profile: { peat: 0, sweet: 4, body: 5, fruit: 2 },
    desc: 'ジムビームのスモールバッチ・コレクションの一角。9年熟成・50度という設計で、メープルシロップのような濃密な甘さとどっしりしたボディを持つ。',
    tasting: { nose: 'メープル、トースト、ナッツ', palate: '濃密で甘く、力強いオーク', finish: '長くリッチ' },
  },
  {
    id: 'woodford', cat: 'bourbon', name: 'ウッドフォードリザーブ', nameEn: 'Woodford Reserve',
    sub: 'ケンタッキー', type: 'バーボン', abv: 43.2, price: '4,000〜5,500円',
    tags: ['ポットスチル', '複雑', 'ミントジュレップ'], profile: { peat: 0, sweet: 4, body: 4, fruit: 3 },
    desc: '銅製ポットスチルによる3回蒸溜原酒を含む、丁寧な造りのプレミアムバーボン。ケンタッキーダービー公式カクテル、ミントジュレップの定番ベース。',
    tasting: { nose: 'ドライフルーツ、バニラ、ミント', palate: 'なめらかで複雑、蜂蜜とスパイス', finish: '長くシルキー' },
  },
  {
    id: 'iwharper', cat: 'bourbon', name: 'I.W.ハーパー ゴールドメダル', nameEn: 'I.W. Harper Gold Medal',
    sub: 'ケンタッキー', type: 'バーボン', abv: 40, price: '2,000〜3,000円',
    tags: ['軽快', 'ハイボール向き', 'コスパ'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: '万博で5つの金賞を獲得した歴史を持つ銘柄。バーボンとしては軽快でクセが少なく、日本ではハイボールやソーダ割りの定番として親しまれてきた。',
    tasting: { nose: 'バニラ、コーン、青リンゴ', palate: '軽やかでスムース、ほのかな甘み', finish: 'すっきり短め' },
  },

  /* ============ テネシー ============ */
  {
    id: 'jd-black', cat: 'tennessee', name: 'ジャックダニエル ブラック (Old No.7)', nameEn: "Jack Daniel's Old No.7",
    sub: 'リンチバーグ', type: 'テネシー', abv: 40, price: '2,500〜3,500円',
    tags: ['定番', 'まろやか', 'コークハイ'], profile: { peat: 0, sweet: 4, body: 3, fruit: 2 },
    desc: '世界で最も有名なアメリカンウイスキー。サトウカエデの炭で濾過されたまろやかな口当たりと、バナナを思わせる甘い香りが特徴。コーラ割りが定番。',
    tasting: { nose: 'バニラ、バナナ、キャラメル', palate: 'まろやかで甘い、ほのかな炭の香ばしさ', finish: '穏やかで甘い' },
  },
  {
    id: 'gentleman-jack', cat: 'tennessee', name: 'ジェントルマンジャック', nameEn: 'Gentleman Jack',
    sub: 'リンチバーグ', type: 'テネシー', abv: 40, price: '3,500〜4,500円',
    tags: ['2回炭濾過', '滑らか', '上品'], profile: { peat: 0, sweet: 4, body: 3, fruit: 3 },
    desc: '樽詰め前と瓶詰め前の2回、炭濾過を行う贅沢な造り。刺激が徹底的に削がれ、シルクのようななめらかさを実現している。ストレートで真価がわかる。',
    tasting: { nose: '柔らかいバニラ、蜂蜜、柑橘', palate: '極めてなめらか、優しい甘み', finish: 'クリーンで穏やか' },
  },
  {
    id: 'jd-single', cat: 'tennessee', name: 'ジャックダニエル シングルバレル', nameEn: "Jack Daniel's Single Barrel Select",
    sub: 'リンチバーグ', type: 'テネシー', abv: 47, price: '6,000〜8,000円',
    tags: ['シングルバレル', '濃厚', '47度'], profile: { peat: 0, sweet: 4, body: 5, fruit: 2 },
    desc: '倉庫最上階の樽から厳選した単一樽ボトリング。47度の濃度でスパイスとオークが力強く立ち上がり、通常のブラックとは別物のような密度がある。',
    tasting: { nose: '濃いバニラ、トースト、キャラメル', palate: '力強く濃厚、スパイシーなオーク', finish: '長く温かい' },
  },
  {
    id: 'dickel12', cat: 'tennessee', name: 'ジョージ・ディッケル No.12', nameEn: 'George Dickel No.12',
    sub: 'カスケードホロウ', type: 'テネシー', abv: 45, price: '3,500〜4,500円',
    tags: ['冷却炭濾過', 'ミネラル', '通好み'], profile: { peat: 0, sweet: 4, body: 4, fruit: 2 },
    desc: '原酒を冷却してから炭濾過する独自製法で、雑味のないクリアな味わいに仕上げる。ジャックダニエルよりドライでミネラル感があり、通好みの評価が高い。',
    tasting: { nose: 'ミネラル、バニラ、コーンブレッド', palate: 'ドライで滑らか、香ばしい甘み', finish: 'クリーンで中程度' },
  },

  /* ============ ライ ============ */
  {
    id: 'bulleit-rye', cat: 'rye', name: 'ブレット ライ', nameEn: 'Bulleit Rye',
    sub: 'ケンタッキー', type: 'ライ', abv: 45, price: '3,500〜4,500円',
    tags: ['95%ライ', 'スパイシー', 'カクテル向き'], profile: { peat: 0, sweet: 2, body: 3, fruit: 2 },
    desc: 'ライ麦比率95%という潔いレシピ。ディルやミントを思わせる清涼なハーブ感と黒胡椒のスパイスが鮮烈で、カクテルにすると輪郭がまったくぼやけない。',
    tasting: { nose: 'ディル、ミント、黒胡椒', palate: 'ドライでスパイシー、清涼感', finish: '長くドライ、スパイスが残る' },
  },
  {
    id: 'rittenhouse', cat: 'rye', name: 'リッテンハウス ライ ボンデッド', nameEn: 'Rittenhouse Rye Bottled-in-Bond',
    sub: 'ケンタッキー', type: 'ライ', abv: 50, price: '4,000〜5,500円',
    tags: ['ボンデッド', '50度', 'バーテンダー定番'], profile: { peat: 0, sweet: 3, body: 4, fruit: 2 },
    desc: '「ボトルド・イン・ボンド」規格（単一蒸溜所・単一シーズン・4年以上・50度）を守る硬派なライ。バーテンダーがマンハッタンに指名する定番中の定番。',
    tasting: { nose: 'シナモン、キャラメル、ライ麦', palate: '厚みのあるスパイス、しっかり甘い', finish: '力強く長い' },
  },
  {
    id: 'sazerac-rye', cat: 'rye', name: 'サゼラック ライ', nameEn: 'Sazerac Rye',
    sub: 'ケンタッキー', type: 'ライ', abv: 45, price: '5,000〜7,000円',
    tags: ['名作カクテル', 'アニス', 'バランス'], profile: { peat: 0, sweet: 3, body: 3, fruit: 3 },
    desc: '世界最古のカクテルとも言われる「サゼラック」の名を冠した一本。ライらしいスパイスがありながら、アニスや柑橘の甘やかさも備えたバランス型。',
    tasting: { nose: 'アニス、柑橘、バニラ', palate: 'スパイシーだが丸い、蜂蜜の甘み', finish: 'なめらかで長め' },
  },
  {
    id: 'knobcreek-rye', cat: 'rye', name: 'ノブクリーク ライ', nameEn: 'Knob Creek Rye',
    sub: 'ケンタッキー', type: 'ライ', abv: 50, price: '4,500〜6,000円',
    tags: ['50度', '濃厚', 'バランス'], profile: { peat: 0, sweet: 3, body: 4, fruit: 2 },
    desc: 'ライの鋭さとバーボン的な甘い厚みを両立させた設計。50度のボディがしっかりしているため、加水しても味が崩れずカクテルの主役を張れる。',
    tasting: { nose: 'ライ麦、バニラ、オーク', palate: '甘みとスパイスが同時に来る、力強い', finish: '長くスパイシー' },
  },
  {
    id: 'whistlepig10', cat: 'rye', name: 'ホイッスルピッグ 10年', nameEn: 'WhistlePig 10 Year Old',
    sub: 'バーモント', type: 'ライ', abv: 50, price: '12,000〜18,000円',
    tags: ['100%ライ', '高級', 'クラフト'], profile: { peat: 0, sweet: 3, body: 4, fruit: 3 },
    desc: '100%ライ麦・10年熟成・50度という贅沢な仕様のクラフトライ。ライの鋭さが長い熟成でまろやかに丸められ、キャラメルとオレンジの甘さが広がる。',
    tasting: { nose: 'キャラメル、オレンジピール、ライスパイス', palate: '濃厚でリッチ、スパイスと甘みが層になる', finish: '非常に長く複雑' },
  },

  /* ============ ジャパニーズ ============ */
  {
    id: 'yamazaki12', cat: 'japanese', name: '山崎 12年', nameEn: 'The Yamazaki 12 Year Old',
    sub: 'サントリー / 大阪', type: 'シングルモルト', abv: 43, price: '25,000〜40,000円',
    tags: ['ミズナラ', '入手難', '名作'], profile: { peat: 0, sweet: 4, body: 4, fruit: 5 },
    desc: '日本のシングルモルトを世界に認めさせた金字塔。シェリー樽とミズナラ樽由来の、熟した果実と白檀のようなオリエンタルな香りが重なる。現在は極めて入手困難。',
    tasting: { nose: '熟した果実、蜂蜜、白檀（ミズナラ）', palate: 'ふくよかで甘い、複雑な果実味', finish: '長く甘美、伽羅の香りが残る' },
  },
  {
    id: 'hakushu12', cat: 'japanese', name: '白州 12年', nameEn: 'The Hakushu 12 Year Old',
    sub: 'サントリー / 山梨', type: 'シングルモルト', abv: 43, price: '25,000〜40,000円',
    tags: ['爽快', 'ミント', '入手難'], profile: { peat: 2, sweet: 3, body: 2, fruit: 4 },
    desc: '南アルプスの森に囲まれた「森の蒸溜所」。若葉やミントを思わせる爽快な香りと、ごく軽いスモークが特徴。ソーダで割った「森香るハイボール」が有名。',
    tasting: { nose: 'ミント、青リンゴ、若葉、微かな煙', palate: '爽やかで軽快、柑橘とハーブ', finish: 'すっきりと清涼感のあるスモーク' },
  },
  {
    id: 'hibiki-bc', cat: 'japanese', name: "響 BLENDER'S CHOICE", nameEn: "Hibiki Blender's Choice",
    sub: 'サントリー', type: 'ブレンデッド', abv: 43, price: '20,000〜30,000円',
    tags: ['ブレンデッド', 'ワイン樽', '華やか'], profile: { peat: 0, sweet: 5, body: 4, fruit: 5 },
    desc: '24面カットのボトルで知られる日本のプレステージブレンデッド。ワイン樽熟成原酒を含み、赤い果実の華やかさと蜂蜜のような甘さが幾層にも重なる。',
    tasting: { nose: 'ベリー、蜂蜜、バラ、ミズナラ', palate: '甘くふくよか、絹のようになめらか', finish: '極めて長く華やか' },
  },
  {
    id: 'yoichi', cat: 'japanese', name: 'シングルモルト余市', nameEn: 'Single Malt Yoichi',
    sub: 'ニッカ / 北海道', type: 'シングルモルト', abv: 45, price: '6,000〜9,000円',
    tags: ['石炭直火', '力強い', '潮'], profile: { peat: 3, sweet: 3, body: 5, fruit: 2 },
    desc: '竹鶴政孝がスコットランドに最も似た地として選んだ余市。世界的にも稀な石炭直火蒸溜が、香ばしく力強い骨格とほのかな潮の香りを生む。',
    tasting: { nose: '焚き火、潮風、ドライフルーツ', palate: '力強くコクがあり、ほろ苦い香ばしさ', finish: '長く重厚、スモークが残る' },
  },
  {
    id: 'miyagikyo', cat: 'japanese', name: 'シングルモルト宮城峡', nameEn: 'Single Malt Miyagikyo',
    sub: 'ニッカ / 宮城', type: 'シングルモルト', abv: 45, price: '6,000〜9,000円',
    tags: ['華やか', 'シェリー', 'なめらか'], profile: { peat: 0, sweet: 4, body: 3, fruit: 5 },
    desc: '余市とは対照的に、蒸気間接蒸溜による華やかで柔らかい酒質。シェリー樽由来のレーズンや赤い果実の甘さが前面に出る、女性的と評される一本。',
    tasting: { nose: 'レーズン、赤い果実、バニラ', palate: 'なめらかで華やか、甘い果実味', finish: '穏やかで甘く長い' },
  },
  {
    id: 'taketsuru', cat: 'japanese', name: '竹鶴 ピュアモルト', nameEn: 'Taketsuru Pure Malt',
    sub: 'ニッカ', type: 'ブレンデッドモルト', abv: 43, price: '7,000〜10,000円',
    tags: ['ピュアモルト', 'バランス', '入手難'], profile: { peat: 2, sweet: 4, body: 4, fruit: 4 },
    desc: '余市と宮城峡のモルト原酒だけをブレンドした、ニッカの理念を体現する一本。力強さと華やかさが絶妙な比率で溶け合っている。',
    tasting: { nose: 'ドライフルーツ、蜂蜜、微かな煙', palate: 'バランスの取れた甘みとコク', finish: '長くまろやか' },
  },
  {
    id: 'chita', cat: 'japanese', name: '知多', nameEn: 'The Chita',
    sub: 'サントリー / 愛知', type: 'シングルグレーン', abv: 43, price: '4,500〜6,500円',
    tags: ['グレーン', '軽やか', '食中酒'], profile: { peat: 0, sweet: 4, body: 1, fruit: 3 },
    desc: '日本を代表するシングルグレーン。「風香るハイボール」というコンセプト通り、驚くほど軽やかで甘く、食事の邪魔をしない。和食との相性は随一。',
    tasting: { nose: 'バニラ、蜂蜜、白い花', palate: '軽快で優しい甘み、ほのかなビター', finish: 'すっきりクリーン' },
  },
  {
    id: 'fuji-sg', cat: 'japanese', name: 'キリンシングルグレーンウイスキー 富士', nameEn: 'Kirin Single Grain Fuji',
    sub: 'キリン / 静岡', type: 'シングルグレーン', abv: 46, price: '5,000〜7,000円',
    tags: ['グレーン', '3種蒸溜機', '高評価'], profile: { peat: 0, sweet: 4, body: 3, fruit: 4 },
    desc: '3種類の蒸溜設備で造り分けたグレーン原酒をブレンドする世界的にも珍しい造り。グレーンとは思えない厚みと、洋梨やエクレアのような甘い香りを持つ。',
    tasting: { nose: '洋梨、カスタード、バニラ', palate: '甘く厚みがあり、なめらか', finish: '甘く長い' },
  },
  {
    id: 'ichiros-mwr', cat: 'japanese', name: 'イチローズモルト＆グレーン ホワイトラベル', nameEn: "Ichiro's Malt & Grain White Label",
    sub: 'ベンチャーウイスキー / 埼玉', type: 'ワールドブレンデッド', abv: 46, price: '5,000〜8,000円',
    tags: ['クラフト', 'ワールドブレンド', '46度'], profile: { peat: 2, sweet: 3, body: 3, fruit: 4 },
    desc: '秩父蒸溜所を率いる肥土伊知郎氏が、世界5大産地の原酒と自社秩父原酒をブレンドした意欲作。バランスが良く、クラフト蒸溜所の実力を示す一本。',
    tasting: { nose: 'バニラ、柑橘、微かな煙', palate: '厚みとキレが同居、甘みとスパイス', finish: '中程度でクリーン' },
  },
  {
    id: 'kakubin', cat: 'japanese', name: 'サントリー 角瓶', nameEn: 'Suntory Kakubin',
    sub: 'サントリー', type: 'ブレンデッド', abv: 40, price: '1,800〜2,500円',
    tags: ['ハイボール', '定番', 'コスパ'], profile: { peat: 0, sweet: 3, body: 2, fruit: 3 },
    desc: '1937年発売、亀甲模様のボトルでおなじみの国民的ウイスキー。日本のハイボール文化を作った立役者で、揚げ物や焼き鳥との相性は抜群。',
    tasting: { nose: 'バニラ、甘い麦、柑橘', palate: '厚みのある甘さとドライな後口', finish: 'キレが良くすっきり' },
  },

  /* ============ カナディアン ============ */
  {
    id: 'canadianclub', cat: 'canadian', name: 'カナディアンクラブ', nameEn: 'Canadian Club',
    sub: 'オンタリオ', type: 'カナディアン', abv: 40, price: '1,500〜2,200円',
    tags: ['軽快', 'コスパ', 'ハイボール向き'], profile: { peat: 0, sweet: 3, body: 1, fruit: 3 },
    desc: '1858年創業、禁酒法時代にアメリカへ密輸されて名を上げた歴史を持つ。極めてライトでクセがなく、ハイボールやジンジャーエール割りに最適。',
    tasting: { nose: 'バニラ、ライ麦、柑橘', palate: 'とても軽快、ほのかな甘みとスパイス', finish: '短くクリーン' },
  },
  {
    id: 'crownroyal', cat: 'canadian', name: 'クラウンローヤル', nameEn: 'Crown Royal',
    sub: 'マニトバ', type: 'カナディアン', abv: 40, price: '3,000〜4,000円',
    tags: ['王室献上', 'まろやか', '紫の袋'], profile: { peat: 0, sweet: 4, body: 2, fruit: 3 },
    desc: '1939年の英国国王夫妻カナダ訪問を記念して献上された銘柄。50種の原酒をブレンドし、王冠型ボトルと紫の巾着で知られる。柔らかく甘い口当たり。',
    tasting: { nose: 'バニラ、蜂蜜、ドライフルーツ', palate: 'なめらかで甘い、軽いスパイス', finish: '穏やかで丸い' },
  },
  {
    id: 'alberta-premium', cat: 'canadian', name: 'アルバータ プレミアム', nameEn: 'Alberta Premium',
    sub: 'アルバータ', type: 'カナディアン', abv: 40, price: '3,000〜4,500円',
    tags: ['100%ライ', 'スパイシー', '通好み'], profile: { peat: 0, sweet: 3, body: 3, fruit: 2 },
    desc: 'カナダには珍しい100%ライ麦原料。軽快なカナディアンの枠にありながら、はっきりしたライのスパイスとハーブ感を持ち、評論家からの評価も高い。',
    tasting: { nose: 'ライ麦、ディル、キャラメル', palate: 'スパイシーで軽やか、蜂蜜の甘み', finish: 'ドライで中程度' },
  },
  {
    id: 'canadianmist', cat: 'canadian', name: 'カナディアンミスト', nameEn: 'Canadian Mist',
    sub: 'オンタリオ', type: 'カナディアン', abv: 40, price: '1,300〜1,900円',
    tags: ['ライト', 'コスパ', '割り材向き'], profile: { peat: 0, sweet: 3, body: 1, fruit: 2 },
    desc: '5大ウイスキーの中でも屈指の軽さとコストパフォーマンス。主張が少ないため、カクテルや炭酸割りのベースとして気軽に使える。',
    tasting: { nose: '穀物、バニラ、淡い果実', palate: '極めてライトで滑らか', finish: 'ごく短くクリーン' },
  },

  /* ============ ワールド ============ */
  {
    id: 'kavalan-classic', cat: 'world', name: 'カバラン クラシック', nameEn: 'Kavalan Classic',
    sub: '台湾 / 宜蘭', type: 'シングルモルト', abv: 40, price: '8,000〜12,000円',
    tags: ['トロピカル', '急速熟成', '高評価'], profile: { peat: 0, sweet: 5, body: 4, fruit: 5 },
    desc: '台湾の亜熱帯気候による急速熟成で、若い原酒とは思えない濃密さを実現。マンゴーやパイナップルのトロピカルな甘い香りが圧倒的に立ち上がる。',
    tasting: { nose: 'マンゴー、パイナップル、バニラ', palate: '非常に甘くリッチ、トロピカルフルーツ', finish: '甘く長い' },
  },
  {
    id: 'kavalan-solist-sherry', cat: 'world', name: 'カバラン ソリスト シェリーカスク', nameEn: 'Kavalan Solist Sherry Cask',
    sub: '台湾 / 宜蘭', type: 'シングルモルト（CS）', abv: 57, price: '25,000〜40,000円',
    tags: ['カスクストレングス', 'シェリー', '濃厚'], profile: { peat: 0, sweet: 5, body: 5, fruit: 5 },
    desc: '単一のシェリー樽から加水せず瓶詰めするカスクストレングス。度数は樽ごとに異なる。凝縮したドライフルーツとチョコレートの、暴力的なまでの濃厚さ。',
    tasting: { nose: '濃密なレーズン、チョコ、シェリー', palate: '極めて濃厚、甘く重層的', finish: '果てしなく長い' },
  },
  {
    id: 'amrut-fusion', cat: 'world', name: 'アムルット フュージョン', nameEn: 'Amrut Fusion',
    sub: 'インド / バンガロール', type: 'シングルモルト', abv: 50, price: '8,000〜12,000円',
    tags: ['50度', 'ピート混合', '高評価'], profile: { peat: 3, sweet: 4, body: 5, fruit: 4 },
    desc: 'インド産大麦とスコットランド産ピーテッド大麦を「融合（フュージョン）」させた意欲作。ジム・マーレイが世界3位と評したことで一躍有名になった。',
    tasting: { nose: '甘い煙、オレンジ、スパイス', palate: '厚くリッチ、スモークと果実が絡む', finish: '長く温かい' },
  },
  {
    id: 'pauljohn-brilliance', cat: 'world', name: 'ポールジョン ブリリアンス', nameEn: 'Paul John Brilliance',
    sub: 'インド / ゴア', type: 'シングルモルト', abv: 46, price: '6,000〜9,000円',
    tags: ['ノンピート', '蜂蜜', '46度'], profile: { peat: 0, sweet: 5, body: 4, fruit: 4 },
    desc: 'インド・ゴア州の海沿いで熟成される、ノンピートのシングルモルト。六条大麦由来の力強い麦感と、蜂蜜のような甘さが厚く広がる。',
    tasting: { nose: '蜂蜜、バニラ、熟した果実', palate: '甘くリッチ、麦の厚み', finish: 'スパイシーで長め' },
  },
  {
    id: 'mackmyra-bruks', cat: 'world', name: 'マクミラ ブルークスウイスキー', nameEn: 'Mackmyra Brukswhisky',
    sub: 'スウェーデン', type: 'シングルモルト', abv: 41.4, price: '6,000〜8,500円',
    tags: ['北欧', 'ジュニパー', '個性派'], profile: { peat: 1, sweet: 3, body: 3, fruit: 4 },
    desc: 'スウェーデン産大麦を地元の泥炭とジュニパー（ネズの木）で燻す、北欧ならではの造り。ハーブ的な清涼感と柔らかい果実味が同居する。',
    tasting: { nose: 'ジュニパー、柑橘、バニラ', palate: 'ハーブとフルーツ、穏やかな甘み', finish: '爽やかで中程度' },
  },
];

const PROFILE_LABELS = {
  peat: 'スモーキー',
  sweet: '甘み',
  body: 'ボディ',
  fruit: '果実感',
};
